jobs: [
  {
    uid: 1,
    title: 'Web Developer',
    role: 'Freelance',
    location: 'Remote',
    category: 'IT', apply_link: 'https://lnkd.in/e6Hpt9Sj',
    company: 'Radix',
    company_link: 'www.radix.com.br',
    company_img: 'https://vagaspm.netlify.app/refresh.png',
    company_category: 'IT Services and IT Consulting',
    company_tag: '',
    job_description: 'descript',
  },
  {
    uid: 2,
    title: 'Software Engineer',
    role: 'Full-time',
    location: 'New York',
    category: 'IT', apply_link: 'https://lnkd.in/e6Hpt9Sj',
    company: 'Radix',
    company_link: 'www.radix.com.br',
    company_img: 'https://vagaspm.netlify.app/refresh.png',
    company_category: 'IT Services and IT Consulting',
    company_tag: '',
    job_description: 'descript',
  },
  {
    uid: 3,
    title: 'Project Manager',
    role: 'Part-time',
    location: 'San Francisco',
    category: 'Management', apply_link: 'https://lnkd.in/e6Hpt9Sj',
    company: 'Radix',
    company_link: 'www.radix.com.br',
    company_img: 'https://vagaspm.netlify.app/refresh.png',
    company_category: 'IT Services and IT Consulting',
    company_tag: '',
    job_description: 'descript',
  },
  {
    uid: 4,
    title: 'Intern',
    role: 'Internship',
    location: 'Los Angeles',
    category: 'IT', apply_link: 'https://lnkd.in/e6Hpt9Sj',
    company: 'Radix',
    company_link: 'www.radix.com.br',
    company_img: 'https://vagaspm.netlify.app/refresh.png',
    company_category: 'IT Services and IT Consulting',
    company_tag: '',
    job_description: 'descript',
  },
  {
    uid: 5,
    title: 'Graphic Designer',
    role: 'Freelance',
    location: 'Remote',
    category: 'Design', apply_link: 'https://lnkd.in/e6Hpt9Sj',
    company: 'Radix',
    company_link: 'www.radix.com.br',
    company_img: 'https://vagaspm.netlify.app/refresh.png',
    company_category: 'IT Services and IT Consulting',
    company_tag: '',
    job_description: 'descript',
  },
  {
    uid: 6,
    title: 'Data Scientist',
    role: 'Full-time',
    location: 'Chicago',
    category: 'Data', apply_link: 'https://lnkd.in/e6Hpt9Sj',
    company: 'Radix',
    company_link: 'www.radix.com.br',
    company_img: 'https://vagaspm.netlify.app/refresh.png',
    company_category: 'IT Services and IT Consulting',
    company_tag: '',
    job_description: 'descript',
  }, {
    uid: '803b5f28-33ca-43a1-acc9-37a8ca2c565f',
    title: 'Profissional de Product Owner Júnior ',
    role: 'Freelance',
    location: 'Remoto',
    apply_link: 'https://lnkd.in/e6Hpt9Sj',
    category: 'Product Owner',
    company: 'Radix',
    company_link: 'www.radix.com.br',
    company_img: 'https://vagaspm.netlify.app/refresh.png',
    company_category: 'IT Services and IT Consulting',
    company_tag: '',
    job_description: 'descript',
  },
  {
    uid: '2a229012-c253-4cbd-84c8-889678817dc3',
    title: 'Analista de Desenvolvimento de Produtos Sênior',
    role: 'Tempo Integral',
    location: 'Posto',
    apply_link: 'https://www.linkedin.com/jobs/view/3916621604/',
    category: 'Cheio de gás',
    company: 'Ipiranga',
    company_link: 'www.ipiranga.com.br',
    company_img: '',
    company_category: 'Gasolina',
    company_tag: 'ipi ipi ipiranga',
    job_description: 'descript',
  },
  {
    uid: '0cbb94c4-db5c-4dcf-a303-75ccee696ea4',
    title: 'Analista de Desenvolvimento de Produtos Sênior',
    role: 'Tempo Integral',
    location: 'Posto',
    apply_link: 'https://www.linkedin.com/jobs/view/3916621604/',
    category: 'Cheio de gás',
    company: 'Ipiranga',
    company_link: 'www.ipiranga.com.br',
    company_img: '',
    company_category: 'Gasolina',
    company_tag: 'ipi ipi ipiranga',
    job_description: 'descript',
  },
  {
    uid: 'asdasd',
    title: 'Analista de Desenvolvimento de Produtos Sênior',
    role: 'Tempo Integral',
    location: 'Posto',
    apply_link: 'https://www.linkedin.com/jobs/view/3916621604/',
    category: 'Cheio de gás',
    company: 'Ipiranga',
    company_link: 'www.ipiranga.com.br',
    company_img: '',
    company_category: 'Gasolina',
    company_tag: 'ipi ipi ipiranga',
    job_description: 'descript',
  },
  {
    uid: 'd2',
    title: 'Analista de Desenvolvimento de Produtos Sênior',
    role: 'Tempo Integral',
    location: 'Posto',
    apply_link: 'https://www.linkedin.com/jobs/view/3916621604/',
    category: 'Cheio de gás',
    company: 'Ipiranga',
    company_link: 'www.ipiranga.com.br',
    company_img: '',
    company_category: 'Gasolina',
    company_tag: 'ipi ipi ipiranga',
    job_description: 'descript',
  },
]